version: 0.0
os: linux

files:
  - source: /
    destination: /opt/vinil-app
permissions:
  - object: /opt/vinil-app/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root