spring:
  profiles:
    include: db
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.ssafy.happyhouse5.dto